 const unAuthToken = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NzRmZDZjYTg4ZjI2YmIyYzY5NjVlODEiLCJlbWFpbCI6InRlc3RAZ2ltbWVsLmllIiwiY2hhbm5lbElkIjoiNjc0ZmQ2Y2E4OGYyNmJiMmM2OTY1ZTgzIiwiaWF0IjoxNzQwMTIyNzE0fQ.ihYPUmBIdMDbEahGsXHurPQMsPgRg2BnwUhgobJx_Kc'

 export default unAuthToken;