 const unAuthToken = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2N2NhZjJlYTA4NDNhY2UyNGJlYTA3NTQiLCJlbWFpbCI6ImdpbW1lbEAxMjMuY29tIiwiY2hhbm5lbElkIjoiNjdjYWYyZWEwODQzYWNlMjRiZWEwNzU2IiwiaWF0IjoxNzQzMjM5MDExfQ.fpsylHalIcpi0ZDsZAK6yCgMtGDf02n_8RU-cyzkILQ'

 export default unAuthToken;