const authBaseUrl = 'https://api.gimmel.one/';


export const ApiConfig = {
  // =========EndPoints==========
  login: 'api/signin',
  signIn:'api/signup',
  onBoarding:'api/onboarding',
  teaching:'api/teachtopic',
  Content:'api/contentmaturity',
  Teachinglocations:'api/teachlocation',
  Education:'api/education',
  HomeGetPost:'api/post',
  Notintrested:'api/notintrestedChannel',
  PostSave:'api/savepost',
  SubstanceUser:'api/substance',
  Health:'api/mentalHealth',
  Neuro:'api/neuroscience',
  Social:'api/social',
  Interestfilter:'api/update/interest',
  Search:'api/search',
  Slider:'api/getposts',
  HistoryList:'api/getHistory',
  getFolder:'api/folders',
  createFolder:'api/folders',
  deleteFolders:'api/deleteFolder/',
  getReviews :'api/getReview/',
  comment:'api/reviews',
  reviewLike:'api/likes/',
  rewiewDislike:'api/dislike/',
  profileEdit:'api/editProfile',
  profileInfo:'api/getProfile',
  RenameFolder:'api/updateFolder/',
  onBoardingInterest:'api/personalTopic',
  educationalObjective:'api/personalEducation',
  saveVideo:'api/getVideosInFolder/',
  myLibraryVideo:'api/vidoesLibrary',
  watchHistoryVideo:'api/getWatchHistory',
  saveVideos:'api/addVideo',
  notIntrestedTopic:'api/notintrestedTopic',
  reportPost:'api/ReportPost',
  sharePost:"api/sharePost",
  SaveIntrest:'api/saveInterest',
  TopicCode:"api/topicPosts",
  MoreLIkeThis:"api/moreLikeThis",
  requestGetList:"api/request",
  Createrequest:"api/request",
  GetSubFolders:"api/get-Subfolders/",
  createSubFolder:"api/subFolders/",
  deleteSubFolder:"api/deleteSubFolder/",
  renameSubFolder:"api/updateSubFolder/",
  subfolderSaveVideo:"api/getVideosInSubFolder/",
  saveSubFolderVideo:"api/addVideoSubfolder",
  getCategories:"api/getByCategories",
  categoriesVideo:"api/getAllCategories",
  replayOnPost:"api/reply",
  getVideoInRequest:"api/getVideos/",
  requestVideo:"api/requestedVideos",
  requestSaveVideo:"api/saveVideos/",
  quiz:"api/saveQuizQuestions/",
    // quiz:"api/saveQuizQuestions/",material questions;

  Quiz:"api/getQuizzes/",
  Discussion: "api/getDiscussion/",
  Homework: "api/getHomework/",
  Activity: "api/getActivity/",
  Test: "api/getTestPoints/",

  QuizPdf:'api/quiz_pdf/',
  DiscussionPdf:'api/discussion_pdf/',
  HomeworkPdf:'api/homework_pdf/',
  ActivityPdf:'api/activity_pdf/',
  TestPdf:'api/test_pdf/',
  RemoveSaggation:"api/removeSuggestions",
  getReviewsReply:"api/getReply/",
  getOneVideo:"api/getPost/",
  homegetvideoid:"api/getPost",
  skipData:"api/saveGenratedContent",
  google:"api/auth/google",
  Suggested:"api/getSuggested/",

  // <----------------------->

  //
  authBaseUrl: `${authBaseUrl}`,
  //
};
